spring:
  datasource:
    url: jdbc:h2:mem:pricedb
    username: sa
    password:

server:
  servlet:
    context-path: /api

pricesource:
  binance:
    url: https://api.binance.com/api/v3/ticker/bookTicker
  houbi:
    url: https://api.huobi.pro/market/tickers